{
  "formatVersion": "1.1",
  "component": {
    "group": "com.coniq.sdk",
    "module": "coniqSDK",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "coniqSDK-1.0.0.aar",
          "url": "coniqSDK-1.0.0.aar",
          "size": 270485,
          "sha512": "491acb26f49863d9e96d018159e21fb7df2d8d5913129c4abf57c4a1db1e2bf16ac487da3ee701f02062d085e3680cc133b8f873862917ea9af258db648aa37e",
          "sha256": "e652759019d584e1e011c96f79b5d731c342618bd7bb769ed32a329cfca0c395",
          "sha1": "20849c143a2cd73218a14c3697f762725f0da352",
          "md5": "2db2e995b2c3c0ec5dbf9f8f51cf34aa"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "coniqSDK-1.0.0.aar",
          "url": "coniqSDK-1.0.0.aar",
          "size": 270485,
          "sha512": "491acb26f49863d9e96d018159e21fb7df2d8d5913129c4abf57c4a1db1e2bf16ac487da3ee701f02062d085e3680cc133b8f873862917ea9af258db648aa37e",
          "sha256": "e652759019d584e1e011c96f79b5d731c342618bd7bb769ed32a329cfca0c395",
          "sha1": "20849c143a2cd73218a14c3697f762725f0da352",
          "md5": "2db2e995b2c3c0ec5dbf9f8f51cf34aa"
        }
      ]
    }
  ]
}
